---
- name: set variable for dated text file
  set_fact:
    dated_file_name: "{{ research_monitor_output_file_location }}/{{ date_stamp }}.txt"
  tags: nightly

- name: create empty logfile
  become: yes
  become_method: sudo
  file:
    dest: "{{ dated_file_name }}"
    state: touch
  tags: nightly

- name: folder sizes for nightly monitor script for research environment
# shell: "du --max-depth=2 {{ item }} >> {{ dated_file_name }}"
  shell: "du --max-depth=1 {{ item }} >> {{ dated_file_name }}"
  with_items: "{{ research_nightly_monitor_locations }}"
  tags: nightly
